#!/usr/bin/env bash

set -e

WORKSPACES=$(i3-msg -t get_workspaces)

if [ -z "$1" ]; then
  WORKSPACE=$(echo "$WORKSPACES" | jq -r 'map(.name) | join("\n")' | rofi -dmenu)
else
  IDX=$1
  FOCUSED_OUTPUT=$(echo "$WORKSPACES" | jq -r 'map(select(.focused))[0].output')
  WORKSPACE=$(echo "$WORKSPACES" | jq -er "map(select(.output == \"$FOCUSED_OUTPUT\"))[$IDX - 1].name")
fi

if [ "$2" = "move" ]; then
  i3-msg move container to workspace "$WORKSPACE"
else
  i3-msg workspace "$WORKSPACE"
fi
