#!/usr/bin/env sh

set -e

mkdir -p ~/Desktop

FILENAME=~/Desktop/"$(date --rfc-3339=seconds)".png

case "$1" in
entire-screen)
  grim "$FILENAME"
  ;;

box)
  slurp | grim -g - "$FILENAME"
  ;;

window)
  swaymsg -t get_tree | \
    jq -r '.. | select(.pid? and .visible?) | .rect | "\(.x),\(.y) \(.width)x\(.height)"' | \
    slurp | grim -g - "$FILENAME"
  ;;

*)
  exit 1
  ;;
esac

pacat --file-format=wav ~/.config/sway/sounds/screenshot.wav
