set rtp+=~/.config/vim
set shell=bash
so ~/.config/vim/shortcuts.vim
so ~/.config/vim/vundle.vim

syntax enable " Enable syntax highlighting
filetype plugin indent on


" General
set backspace=2       " Make backspace delete
set clipboard=unnamed " Make vim share clipboard with system


" Tab indenting
set tabstop=2
set expandtab
set shiftwidth=2
set softtabstop=2
set ai " Autoindent
set si " Smart indent


""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Colorscheme
fun! RefreshBackground()
  execute "set background=".join(readfile($HOME."/.config/colors"))
endfun
fun! RefreshColors()
  call RefreshBackground()
  " Fix issue where airline doesn't refresh when changed by autocmd:
  AirlineTheme solarized
endfun
autocmd CursorHold * call RefreshColors()

try
  colorscheme solarized
  let g:solarized_diffmode="high"
  call RefreshBackground()
catch
  colorscheme hybrid
  set background=dark
endtry
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""


" Appearance
set showtabline=2   " Always show tab bar
set laststatus=2    " Always show the statusline
set ttimeoutlen=50  " Set timeout length
set number          " Show line numbers
set title           " Display filename in title bar
set cursorline      " Adds highlighted line on current line
set cursorcolumn    " Adds highlighted line on current column
set scrolloff=5     " set minimum space between the cursor and window


" Searching
set hlsearch   " Highlight found searches
set ignorecase " Ignore case in searched
set incsearch  " Incrementally search


" Misc
set nobackup        " Don't create backup files
set spelllang=en_us " Set spell check language
set nowrap          " Disable line wrapping
set ttyfast
set tildeop         " Make tilde use motion commands
set autoread        " Read changes on a file when it is changed


" Folding
set foldmethod=syntax
set foldlevel=99


" Show Invisibles
set list
set listchars=tab:»\ ,eol:¬
