#!/usr/bin/env bash

set -e

function section {
  echo
  echo
  echo
  echo "################################################################"
  echo "==> $1"
  echo
}

function ask {
  printf "%s: " "$2"
  read $1
}

section "INSTALLING PACKAGES NEEDED AFTER REBOOT"
ask WIFI "Install wifi-menu? (yes/no)"
[ "$WIFI" == "yes" ] && pacman -S dialog wpa_supplicant
pacman -S \
  dhcpcd \
  intel-ucode \
  netctl \
  sudo \
  vi \
  ;

section "ADDING ENCRYPT TO MKINITCPIO"
vi /etc/mkinitcpio.conf
mkinitcpio -p linux

section "SETTING LOCALE"
echo "en_US.UTF-8 UTF-8" > /etc/locale.gen
locale-gen
echo "LANG=en_US.UTF-8" > /etc/locale.conf
export LANG=en_US.UTF-8
ln -f -s /usr/share/zoneinfo/America/Los_Angeles /etc/localtime
ask HOSTNAME "Hostname"
echo "$HOSTNAME" > /etc/hostname

section "SETTING ROOT PASSWORD"
passwd

section "CREATING MAIN USER"
ask USERNAME "Username"
useradd -m -g users -G wheel "$USERNAME"
passwd "$USERNAME"

section "SETTING UP SIMPLE FIREWALL"
cp /etc/iptables/simple_firewall.rules /etc/iptables/iptables.rules
systemctl enable iptables.service
