let g:tmuxline_preset = {}
let g:tmuxline_separators = {}
" let g:tmuxline_separators.left = '⮀'
" let g:tmuxline_separators.left_alt = '⮁'
" let g:tmuxline_separators.right = '⮂'
" let g:tmuxline_separators.right_alt = '⮃'
let g:tmuxline_separators.space = ' '
let g:tmuxline_preset.win = '#I #W'
let g:tmuxline_preset.cwin = '#I #W'
