#!/usr/bin/env bash

set -e
cd "$(dirname "$0")/profiles"

PROFILE_NAME="$1"
if [ -z "$PROFILE_NAME" ]; then
  PROFILE_NAME=$(ls -d */ | cut -f1 -d/ | rofi -dmenu -p Profile)
fi

firefox --new-instance --profile "$(pwd)/$PROFILE_NAME"
