#!/usr/bin/env bash

XINPUT_LIST=$(xinput list)

function trackpad {
  TRACKPAD_NAME="$1"
  if echo "$XINPUT_LIST" | grep "$TRACKPAD_NAME"; then
    # Enable tap to click
    xinput set-prop "$TRACKPAD_NAME" "libinput Tapping Enabled" 1
    # Disable tap to drag
    xinput set-prop "$TRACKPAD_NAME" "libinput Tapping Drag Enabled" 0
    # Set right click to 2 finger
    xinput set-prop "$TRACKPAD_NAME" "libinput Click Method Enabled" {0 1}
    # Set natural scroll
    xinput set-prop "$TRACKPAD_NAME" "libinput Natural Scrolling Enabled" 1
  fi
}

trackpad "Apple Inc. Magic Trackpad 2"
trackpad "Synaptics TM3289-002"
