#!/usr/bin/env bash

set -e

EXECUTABLE=$(basename "$0")
ARGV=("$@")

BWRAP_PATH="/usr/bin"
DIE_WITH_PARENT=1

BWRAP_ARGS=(
  --dev /dev
  --dir "/run/user/$(id -u)"
  --new-session
  --proc /proc
  --ro-bind /usr /usr
  --setenv BROWSER ''
  --symlink /usr/bin /bin
  --symlink usr/lib /lib
  --symlink usr/lib64 /lib64
  --tmpfs /home/$USER
  --tmpfs /tmp
  --unshare-all
)

function append_path { BWRAP_PATH+=":$1" ; }
function bind { BWRAP_ARGS+=(--bind "$1" "$2") ; }
function read_only { BWRAP_ARGS+=(--ro-bind "$1" "$1") ; }
function read_write { BWRAP_ARGS+=(--bind "$1" "$1") ; }
function ro_bind { BWRAP_ARGS+=(--ro-bind "$1" "$2") ; }

function env {
    BWRAP_ARGS+=(--setenv "$1" "$2") 
}

function camera {
  if [ -e /dev/video0 ]; then
    BWRAP_ARGS+=(--dev-bind /dev/video0 /dev/video0) 
  fi
}

function mount_cwd {
  if [[ "$PWD" != "$HOME"/* ]]; then
    echo "bindcwd cannot be called in $PWD"
    exit 1
  fi
  read_write "$PWD"
}

function read_only_all {
  for MAYBE_PATH in "$@"; do
    if [ -e "$MAYBE_PATH" ]; then
      read_only "$(realpath "$MAYBE_PATH")"
    fi
  done
}

function read_write_all {
  for MAYBE_PATH in "$@"; do
    if [ -e "$MAYBE_PATH" ]; then
      read_write "$(realpath "$MAYBE_PATH")"
    fi
  done
}

function network {
  BWRAP_ARGS+=(
    --ro-bind /etc/ssl /etc/ssl
    --ro-bind /etc/ca-certificates /etc/ca-certificates
    --ro-bind /etc/resolv.conf /etc/resolv.conf
    --share-net
    --hostname RESTRICTED
  )
}

function gui {
  BWRAP_ARGS+=(
    --ro-bind ~/.fonts ~/.fonts
    --ro-bind /etc/fonts /etc/fonts
    --ro-bind /run/user/"$(id -u)"/pulse /run/user/"$(id -u)"/pulse
    --ro-bind "$HOME/.config/dconf" "$HOME/.config/dconf"
  )
  read_only_all /run/user/"$(id -u)"/wayland-*
}

function gpu {
  BWRAP_ARGS+=(
    --dev-bind /dev/dri /dev/dri
    --ro-bind /sys /sys
  )
}

function audio {
  BWRAP_ARGS+=(
    --ro-bind /run/user/"$(id -u)"/pulse /run/user/"$(id -u)"/pulse
  )
}

function daemon {
  DIE_WITH_PARENT=0
}


function dbus {
  BWRAP_ARGS+=(
    --ro-bind /run/user/"$(id -u)"/bus /run/user/"$(id -u)"/bus
  )
}

function finalize_args {
  BWRAP_ARGS+=(--setenv PATH "$BWRAP_PATH")
  if [ $DIE_WITH_PARENT -eq 1 ]; then
    BWRAP_ARGS+=(--die-with-parent)
  fi
}

function run_jail {
  finalize_args
  exec bwrap "${BWRAP_ARGS[@]}" -- "$EXECUTABLE" "${ARGV[@]}"
}

function run_jail_raw {
  finalize_args
  exec bwrap "${BWRAP_ARGS[@]}" "$@"
}
