name: docgen

on:
  push:
    branches:
      - master

jobs:
  docgen:
    runs-on: [ubuntu-latest]
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - run: date +%F > todays-date
    - name: Restore cache for today's nightly.
      uses: actions/cache@v2
      with:
        path: _neovim
        key: ${{ runner.os }}-nightly-${{ hashFiles('todays-date') }}
    - name: Setup from neovim nightly and run docgen
      run: |
        curl -OL https://raw.githubusercontent.com/norcalli/bot-ci/master/scripts/github-actions-setup.sh
        source github-actions-setup.sh nightly-x64
        scripts/docgen.sh
    - name: Commit changes
      env:
        COMMIT_MSG: |
          [docgen] Update CONFIG.md
          skip-checks: true
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add CONFIG.md
        # Only commit and push if we have changes
        git diff --quiet && git diff --staged --quiet || (git commit -m "${COMMIT_MSG}"; git push)
