#!/usr/bin/env bash

INPUT=$1
OUTPUT=$(mktemp --suffix=.png)

EFFECT=(-modulate 70 -filter Gaussian -resize 20% -define filter:sigma=2.5 -resize 500%)


while read WIDTH; do
  read HEIGHT
  read OFFSETX
  read OFFSETY

  RANDOM_IMAGE=$(ls ~/.config/xautolock/images | shuf -n 1)
  LOCK_IMAGE="$HOME/.config/xautolock/images/$RANDOM_IMAGE"
  LOCK_IMAGE_WIDTH=$(identify -format "%w" "$LOCK_IMAGE")
  LOCK_IMAGE_HEIGHT=$(identify -format "%h" "$LOCK_IMAGE")

  X=$(expr $OFFSETX + $WIDTH / 2 - $LOCK_IMAGE_WIDTH / 2)
  Y=$(expr $OFFSETY + $HEIGHT / 2 - $LOCK_IMAGE_HEIGHT / 2)
  EFFECT+=("$LOCK_IMAGE" -geometry "+$X+$Y" -composite)
done < <(xrandr --listactivemonitors | tail +2 | sed -r 's/.*? ([0-9]+)\/([0-9]+)x([0-9]+)\/([0-9]+)\+([0-9]+)\+([0-9]+).*/\1\n\3\n\5\n\6/g')

convert "$INPUT" "${EFFECT[@]}" "$OUTPUT"

echo $OUTPUT
