#!/usr/bin/env sh

IN=$(mktemp --suffix=.png)
maim "$IN"

i3lock -c 000000
OUT=$(~/.config/xautolock/convert-image "$IN")
killall i3lock

i3lock \
  --nofork \
  --tiling \
  --image "$OUT" \
  --ignore-empty-password \
  --show-failed-attempts

rm "$IN" "$OUT"
