#!/usr/bin/env bash

TMP_DIR=$(mktemp -d)

TOTAL_WIDTH=0
TOTAL_HEIGHT=0


while read WIDTH; do
  read HEIGHT
  read X
  read Y


  IMG=$(mktemp --suffix=.jpg "--tmpdir=$TMP_DIR")
  curl -L "https://source.unsplash.com/collection/2190600/${WIDTH}x${HEIGHT}" > $IMG
  sleep 5


  RIGHT_COORD=$(($X + $WIDTH))
  BOTTOM_COORD=$(($Y + $HEIGHT))
  [ "$RIGHT_COORD" -gt "$TOTAL_WIDTH" ] && TOTAL_WIDTH=$RIGHT_COORD
  [ "$BOTTOM_COORD" -gt "$TOTAL_HEIGHT" ] && TOTAL_HEIGHT=$BOTTOM_COORD

  EFFECT+=("$IMG" -geometry "${WIDTH}x${HEIGHT}+$X+$Y!" -composite)
done < <(xrandr --listactivemonitors | tail +2 | sed -r 's/.*? ([0-9]+)\/([0-9]+)x([0-9]+)\/([0-9]+)\+([0-9]+)\+([0-9]+).*/\1\n\3\n\5\n\6/g')

convert -size "${TOTAL_WIDTH}x${TOTAL_HEIGHT}" xc:black "${EFFECT[@]}" "$TMP_DIR/out.jpg"

feh --no-fehbg --bg-tile "$TMP_DIR/out.jpg"
rm -r "$TMP_DIR"
